### ISSUE TITLE
Error on handler.split

### ISSUE THREAD

**Issue by qops1981** [motdotla/node-lambda#113]
Standard install/setup
I was assuming out of the box functionality. Let me know if I just need to fill something in.

```
node-lambda run codeCommitToS3.js 
/usr/lib/node_modules/node-lambda/lib/main.js:41
  var splitHandler = program.handler.split('.');
                                    ^

TypeError: Cannot read property 'split' of undefined
    at Lambda.run (/usr/lib/node_modules/node-lambda/lib/main.js:41:37)
    at Command.<anonymous> (/usr/lib/node_modules/node-lambda/bin/node-lambda:89:12)
    at Command.listener (/usr/lib/node_modules/node-lambda/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/lib/node_modules/node-lambda/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/lib/node_modules/node-lambda/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/lib/node_modules/node-lambda/bin/node-lambda:102:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
my .env

```
AWS_ENVIRONMENT=development
AWS_ACCESS_KEY_ID=your_key
AWS_SECRET_ACCESS_KEY=your_secret
AWS_SESSION_TOKEN=
AWS_ROLE_ARN=your_amazon_role
AWS_REGION=us-east-1
AWS_FUNCTION_NAME=
AWS_HANDLER=index.handler
AWS_MEMORY_SIZE=128
AWS_TIMEOUT=3
AWS_DESCRIPTION=
AWS_RUNTIME=nodejs4.3
AWS_VPC_SUBNETS=
AWS_VPC_SECURITY_GROUPS=
EXCLUDE_GLOBS="event.json"
PACKAGE_DIRECTORY=build
```

**Comment by DeviaVir** [comment]
Are you running `node-lambda` in the same folder as your `.env`? It looks like we can't find your `AWS_HANDLER` (it's trying to split the string, which apparently is not set)

**Comment by DeviaVir** [comment]
Actually, referring to https://github.com/motdotla/node-lambda/blob/master/bin/node-lambda#L18 would set `index.handler` as the default, so that makes me think you're somehow setting that to empty.

**Comment by qops1981** [comment]
I am running it in the same directory as the `.env` file. Should I not? I am pretty green to all this so I will except stupidity as a cause, lol.

**Comment by qops1981** [comment]
Figured it out. It was stupidity. My lack of understanding about what index.handler was for.

**Comment by DeviaVir** [comment]
Ah, alright!
