### ISSUE TITLE
displaying help fails

### ISSUE THREAD

**Issue by gidsg** [motdotla/node-lambda#127]
Displaying help no longer works for me:

Environment info
```
$ node-lambda --version
0.8.5
$ nvm current
v6.3.0
```

Displaying help
```
$ node-lambda -h
/usr/local/lib/node_modules/node-lambda/node_modules/commander/index.js:946
      , cmd.description()
            ^

TypeError: cmd.description is not a function
    at /usr/local/lib/node_modules/node-lambda/node_modules/commander/index.js:946:13
    at Array.map (native)
    at Command.commandHelp (/usr/local/lib/node_modules/node-lambda/node_modules/commander/index.js:936:6)
    at Command.helpInformation (/usr/local/lib/node_modules/node-lambda/node_modules/commander/index.js:993:26)
    at Command.outputHelp (/usr/local/lib/node_modules/node-lambda/node_modules/commander/index.js:1023:32)
    at outputHelpIfNecessary (/usr/local/lib/node_modules/node-lambda/node_modules/commander/index.js:1078:11)
    at Command.parseArgs (/usr/local/lib/node_modules/node-lambda/node_modules/commander/index.js:620:5)
    at Command.parse (/usr/local/lib/node_modules/node-lambda/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-lambda/bin/node-lambda:102:9)
    at Module._compile (module.js:541:32)
```

**Comment by DeviaVir** [comment]
This would've worked if you had specified which command you'd like to have seen the `help` page for, i.e. `node-lambda deploy -h`

#147 makes `deploy` the default and alias so that the help is returned even if you only type `node-lambda -h`.

Thanks for your report and helping us make `node-lambda` better!

**Comment by DeviaVir** [comment]
This change unfortunately exposed a bug with [commander](https://github.com/tj/commander.js/issues/539), that blocked people from using arguments with other commands.

This means that you'll have to use `node-lambda [command] -h` again.
