### ISSUE TITLE
#147 prevents cli options from being used

### ISSUE THREAD

**Issue by smolnikov** [motdotla/node-lambda#149]
#147 changed `deploy` from being command to be alias for whole program. Since that `node-lambda run --handler dir/index.handler` is no longer working:

```
module.js:457
    throw err;
    ^

Error: Cannot find module '/Users/smolnikov/dir/index.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Lambda.run (/Users/smolnikov/dir/node_modules/node-lambda/lib/main.js:50:17)
    at Command.<anonymous> (/Users/smolnikov/dir/node_modules/node-lambda/bin/node-lambda:99:12)
    at Command.listener (/Users/smolnikov/dir/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/smolnikov/dir/node_modules/commander/index.js:615:12)
```

Changing `bin/node-lambda:39` back to `.command('deploy')` solves the problem.

**Comment by DeviaVir** [comment]
@smolnikov thanks for your report, I was unfortunately not able to reproduce your problem. The error stack also seems to contradict the solution you found for the issue you reported.

My output:
```
$ node-lambda run --handler index.handler
Running index.handler
==================================
event { key: 'value', key2: 'value2', other_key: 'other_value' }
==================================
Stopping index.handler!
Success:
$ node-lambda -v
0.8.8
```

Any chance you can give me any tips on how to reproduce your problem?

**Comment by flesch** [comment]
I've reproduced this with a fresh install of [node-lambda-template](https://github.com/motdotla/node-lambda-template) and `index.js` moved to `dist/index.js`.

`node-lambda run --handler dist/index.handler` produces this error:

```
$ node-lambda run --handler dist/index.handler
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/flesch/node-lambda-template/index.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Lambda.run (/Users/flesch/.nvm/versions/node/v4.3.2/lib/node_modules/node-lambda/lib/main.js:50:17)
    at Command.<anonymous> (/Users/flesch/.nvm/versions/node/v4.3.2/lib/node_modules/node-lambda/bin/node-lambda:99:12)
    at Command.listener (/Users/flesch/.nvm/versions/node/v4.3.2/lib/node_modules/node-lambda/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/Users/flesch/.nvm/versions/node/v4.3.2/lib/node_modules/node-lambda/node_modules/commander/index.js:615:12)
```

`--handler` (and `-H`) no longer overwrite the `AWS_HANDLER` variable defined in `.env`.

**Comment by DeviaVir** [comment]
Seems like it may have something to do with this;
https://github.com/tj/commander.js/issues/539

definitely an upstream bug, reverting the change.

**Comment by DeviaVir** [comment]
Thanks for catching this @smolnikov and for the reproduction @flesch! I reverted the `command` solution for now in https://github.com/motdotla/node-lambda/pull/152

**Comment by DeviaVir** [comment]
Available on NPM now, rock on!
