### ISSUE TITLE
node-lambda deploy fails

### ISSUE THREAD

**Issue by wonjun27** [motdotla/node-lambda#161]
node-lambda run works well, but node-lambda fails with the following error, has anyone seen it? Thanks

----

Warning!!! You are building on a platform that is not 64-bit Linux (darwin.x64). If any of your Node dependencies include C-extensions, they may not work as expected in the Lambda environment.

=> Moving files to temporary directory
=> Running npm install --production
/Users/wonjun/.nvm/versions/node/v4.6.0/lib/node_modules/node-lambda/lib/main.js:470
      throw err;
      ^

Error: Command failed: /bin/sh -c npm -s install --production --prefix /var/folders/01/p4pf0hhs7_d7t7hk_x64kyxc0000gn/T/canary-1476780392265

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)

**Comment by wonjun27** [comment]
starting off with https://github.com/motdotla/node-lambda-template works.
