### ISSUE TITLE
Runtime not defined

### ISSUE THREAD

**Issue by grobmeier** [motdotla/node-lambda#187]
A fresh install of node-lambda leads to:

```
ReferenceError: runtime is not defined
    at Lambda._runHandler (/Development/demo/node_modules/node-lambda/lib/main.js:99:27)
    at Lambda.run (/Development/demo/node_modules/node-lambda/lib/main.js:54:8)
    at Command.<anonymous> (/Development/demo/node_modules/node-lambda/bin/node-lambda:101:12)
    at Command.listener (/Development/demo/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/Development/demo/node_modules/commander/index.js:615:12)
    at Command.parse (//Development/demo/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Development/demo/node_modules/node-lambda/bin/node-lambda:113:9)
    at Module._compile (module.js:425:26)
```

Looking at the code, I think the error is right :)
https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L99

**Comment by mbustamanteo** [comment]
I confirm that this problem occurs and this patch solves it

**Comment by markbrouch** [comment]
Thanks for the PR fix. In the meantime before it is accepted, `v0.8.10` is the last working version.

**Comment by markbrouch** [comment]
@DeviaVir please publish this patch.

**Comment by DeviaVir** [comment]
@markbrouch feel free to PR the version bump next time, format is in past PR's and the current one looks like:
https://github.com/motdotla/node-lambda/pull/190

0.8.13 will be published shortly based off of this.
