### ISSUE TITLE
Windows: Command failed: mkdir -p 

### ISSUE THREAD

**Issue by derekmurawsky** [motdotla/node-lambda#196]
Running in windows, mkdir -p throws the following error in both the command prompt and powershell

C:\projects\XXXX> node-lambda package
=> Creating package directory
Warning!!! You are building on a platform that is not 64-bit Linux (win32.x64). If any of your Node dependencies include C-extensions, they may not work as expected in
the Lambda environment.

=> Moving files to temporary directory
C:\Users\XXXX\AppData\Roaming\npm\node_modules\node-lambda\lib\main.js:439
      throw err;
      ^

Error: Command failed: mkdir -p C:\Users\XXXX\AppData\Local\Temp\XXXXXXX
A subdirectory or file C:\Users\XXXXXX\AppData\Local\Temp\XXXXXXXalready exists.
Error occurred while processing: C:\Users\XXXXX\AppData\Local\Temp\XXXXXX

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
 
It successfully creates the temp directory, though.

**Comment by derekmurawsky** [comment]
Just read that windows isn't supported in a previous issue. Closing ticket.
