### ISSUE TITLE
RequestEntityTooLargeException: Request must be smaller than 5120 bytes for the UpdateFunctionConfiguration operation

### ISSUE THREAD

**Issue by EnriqueCanals** [motdotla/node-lambda#212]
I'm in the process of updating all of my lambdas to the latest version (`0.8.15`) to take advantage of the recent addition of  support for node 6.10. I have been able to seamlessly upgrade and deploy all but one of my lambda functions with `0.8.15` but the issue with this one function I can trace back to `0.8.12`- it works fine up through `0.8.11` and was possibly introduced when #181 was closed.

I'm running `node-lambda deploy` as an NPM script and as part of its deploy process I set an environment variable that's an HTML document which ends up being a fairly long string; even still, total size of deploy.env is only ~15KB. This method has worked fine up through `0.8.11` and I just can't seem to figure out why it's breaking in post `0.8.11` versions as there's no limit set on the Environment object in the **UpdateFunctionConfiguration** operation (at least as indicated in the [AWS JavaScript SDK docs](http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html)). I'm going to continue to read through the changes made between `0.8.11` and `0.8.12` to see if I can find a working solution to contribute. In the mean time I figured I should post my issue here in case someone else is experiencing this error or something similar; I did find [this closed issue](https://github.com/motdotla/node-lambda/issues/123) but I can confirm this was working for me up through `0.8.11`. See stack trace below:

```
/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

RequestEntityTooLargeException: Request must be smaller than 5120 bytes for the UpdateFunctionConfiguration operation
    at Object.extractError (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:675:12)
```

***
Just want to give a big thanks to all of the maintainers and contributors for the work they put into this project.

**Comment by EnriqueCanals** [comment]
I see now that there is a limit to the total size of a set of environment variables; [see docs on lambda limits here](http://docs.aws.amazon.com/lambda/latest/dg/limits.html).

**Comment by EnriqueCanals** [comment]
For transparency, this issue came about with the inclusion of env var support in `0.8.12`. Prior to this release environment variables were essentially being set as variables at the top of the function itself, so the 4KB cap was not an issue.

**Comment by DeviaVir** [comment]
Ugh. There's different problems with setting variables on top of the functions, hence the choice to jump on env vars in AWS.
Thanks for taking the effort to document your foray into the void!
