### ISSUE TITLE
deploy command not picking up deploy.env variables

### ISSUE THREAD

**Issue by gitgrimbo** [motdotla/node-lambda#301]
In my `package.json` I have the following `deploy` command in `scripts`:

```
  "scripts": {
    "deploy": "node-lambda deploy --configFile deploy.env --prebuiltDirectory dist",
```

My `deploy.env` is:

```
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=yyy
```

If I log the key and secret key [here](https://github.com/motdotla/node-lambda/blob/987192bd19cdd2ec37a4f458435297cada5d6475/lib/main.js#L700-L701) I get this:

`your_key your_secret`

followed by this error:

`The security token included in the request is invalid.`

```
UnrecognizedClientException: The security token included in the request is invalid.
    at Object.extractError (MY_PROJECT\node_modules\aws-sdk\lib\protocol\json.js:48:27)
    at Request.extractError (MY_PROJECT\node_modules\aws-sdk\lib\protocol\rest_json.js:37:8)
    at Request.callListeners (MY_PROJECT\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (MY_PROJECT\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (MY_PROJECT\node_modules\aws-sdk\lib\request.js:678:14)
    at Request.transition (MY_PROJECT\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (MY_PROJECT\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at MY_PROJECT\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (MY_PROJECT\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (MY_PROJECT\node_modules\aws-sdk\lib\request.js:680:12)
```

I'm not sure what the problem is here.  Can I not use a combination of `--configFile` and other `node-lambda` CLI parameters?

**Comment by abetomo** [comment]
@gitgrimbo 
Running `node-lambda setup` also creates `.env`.
It is good to set `AWS_ACCESS_KEY_ID` etc there.

**Comment by gitgrimbo** [comment]
Thanks. Is that to say using `configFile` doesn't work with `deploy.env` and I should be using no `configFile` argument and a `.env` file instead?

**Comment by abetomo** [comment]
@gitgrimbo 
`.env` is automatically loaded so you do not need to specify options.
`--configFile` and `deploy.env` are used to configure "Environment variables" which can be checked on the web console.

**Comment by gitgrimbo** [comment]
Ah, so `.env` and my `deploy.env` actually serve different purposes?

**Comment by abetomo** [comment]
Yes. The roles of .env and deploy.env are different.

Basically it can be deployed by setting the necessary values in the `.env` created by running `node-lambda setup`.
(Use `deploy.env` to set the environment variables you want to use on Lambda. It can be deployed without setting `deploy.env`.)

**Comment by gitgrimbo** [comment]
Thanks for your help.

**Comment by DeviaVir** [comment]
Should we clarify this better in the docs, or should we close this issue?

**Comment by RickDT** [comment]
Frankly, they do seem a bit backwards. The .env file is used for doing deployments and deploy.env is used for setting ENV vars.

At our company, we rename deploy.env to `secrets` to make it more clear. Would something like that make sense for the setup command?

Rick

**Comment by gitgrimbo** [comment]
One file is for the secrets that are used to connect to AWS (`.env`), the other could be for secrets that are used by the function at run time (`deploy.env` / `secrets`)? I think that's where I was getting mixed up.

**Comment by madorb** [comment]
`build.env` / `runtime.env`? the deploy naming is confusing - it could reasonably be interpretted as either the vars for use in the deployment process or the vars that are deployed by said process.

**Comment by ForzaGreen** [comment]
@abetomo if I want to use only `.env`: 
if I put all my "Environment variables" in `.env`, will this work out ? i.e. will these variables be available in my deployed lambda ?

**Comment by abetomo** [comment]
@ForzaGreen 
Environment variables you wish to use with Lambda Funciton must be set in `deploy.env` and must be specified as an option when deploying.

example:
```
% node-lambda deploy -f ./deploy.env
```
