### ISSUE TITLE
Problems with deployement using file npm local dependency

### ISSUE THREAD

**Issue by vincent-enkidoo** [motdotla/node-lambda#340]
```
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:732:19)
    at tryReadSync (fs.js:487:20)
    at Object.fs.readFileSync (fs.js:535:19)
    at Walker.<anonymous> (/usr/local/lib/node_modules/node-lambda/lib/main.js:423:26)
    at emitOne (events.js:96:13)
    at Walker.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Walker.Readable.push (_stream_readable.js:134:10)
    at /usr/local/lib/node_modules/node-lambda/node_modules/klaw/src/index.js:35:43
```

When installing a local package using
```npm i --save ./modules```

Node version : 6.10.2
NPM version : 5.0.4
Node-lambda version : 0.11.0

**Comment by abetomo** [comment]
Thanks for the report.
Please wait as we fix it soon.

**Comment by abetomo** [comment]
It is an error caused by symlink not handling well when zipping.

We will respond when a new version of the node-archiver used by node-lambda is released.
Please wait for a while.

https://github.com/archiverjs/node-archiver/issues/243
