### ISSUE TITLE
deploy --publish needs a boolean ?

### ISSUE THREAD

**Issue by florent-blanvillain** [motdotla/node-lambda#345]
Hi :)

When I use
`node-lambda deploy --publish true` 

I get
`{ InvalidParameterType: Expected params.Publish to be a boolean
    at ParamValidator.fail (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateType (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/param_validator.js:222:10)
    at ParamValidator.validateScalar (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/param_validator.js:138:21)
    at ParamValidator.validateMember (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/param_validator.js:94:21)
    at ParamValidator.validateStructure (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/event_listeners.js:125:42)
    at Request.callListeners (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
  message: 'Expected params.Publish to be a boolean',
  code: 'InvalidParameterType',
  time: 2017-07-05T07:53:05.244Z }`

Is it a bug or is there a particular value to put ?

Thank you,
Florent

**Comment by abetomo** [comment]
Thanks for the report.
I fixed it because it was a bug. #346
