### ISSUE TITLE
node-lambda deploy with --eventSourceFile using default fails

### ISSUE THREAD

**Issue by medoix** [motdotla/node-lambda#413]
using the default event_sources.json file generated by node-lambda setup

when running node-lambda dpeloy with the --eventSourcefile event_sources.json

=> Moving files to temporary directory
=> Running npm install --production
=> Zipping deployment package
=> Zipping repo. This might take up to 30 seconds
=> Reading zip file to memory
=> Reading event source file to memory
SyntaxError: event_sources.json: Unexpected token } in JSON at position 156
    at JSON.parse (<anonymous>)
    at Object.readFileSync (/usr/local/lib/node_modules/node-lambda/node_modules/jsonfile/index.js:70:17)
    at Lambda._eventSourceList (/usr/local/lib/node_modules/node-lambda/lib/main.js:234:21)
    at Lambda._deployToRegion (/usr/local/lib/node_modules/node-lambda/lib/main.js:764:34)
    at Promise.all.regions.map (/usr/local/lib/node_modules/node-lambda/lib/main.js:895:21)
    at Array.map (<anonymous>)
    at _archive.then (/usr/local/lib/node_modules/node-lambda/lib/main.js:894:34)
    at <anonymous>

**Comment by abetomo** [comment]
@medoix Could you show me the contents of JOSN(event_source.json) used when an error occurred?

**Comment by medoix** [comment]
```
{
  "ScheduleEvents": [
    {
      "ScheduleName": "mylambda",
      "ScheduleState": "ENABLED",
      "ScheduleExpression": "rate(1 minutes)",
    }
  ]
}
```

**Comment by medoix** [comment]
Ok so helps if i JSON lint it and see the error myself... is the , on the 6th line

Fixed that and now get 
`(node:70736) UnhandledPromiseRejectionWarning: ValidationException: Parameter ScheduleExpression is not valid.
    at Request.extractError (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
(node:70736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:70736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by abetomo** [comment]
What about `rate(1 minute)`?
(Delete the last `s`.)

**Comment by medoix** [comment]
Works! thank you.
