### ISSUE TITLE
Local dependencies are not included in final zip file

### ISSUE THREAD

**Issue by vladaman** [motdotla/node-lambda#434]
I might having which may be related to previous issue

Node version : 10.2.1
NPM version : 6.1.0
Node-lambda version : 0.11.7

When we use local dependencies they are not included in final package. Symlink crreated in .lambda folder is invalid. Relative path is invalid. It may be due to changes in npm which include relative and not absolute path in package.json

**Comment by abetomo** [comment]
@vladaman Could you try the `--prebuiltDirectory` option?

https://github.com/motdotla/node-lambda/issues/354#issuecomment-315061169

**Comment by vladaman** [comment]
No, it did not help. I get another error with --prebuildDirectory

Problem may be, that my local modules in node_modules are simlinks. So they cannot be copied.

```
Error: Source and destination must not be the same.
    at checkStats (/usr/lib/node_modules/node-lambda/node_modules/fs-extra/lib/copy/copy.js:237:17)
    at fs.stat (/usr/lib/node_modules/node-lambda/node_modules/fs-extra/lib/copy/copy.js:227:14)
    at /usr/lib/node_modules/node-lambda/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by vladaman** [comment]
So I am not having any luck fixing this. How I setup my project is that I got local dependencies in ../local_modules - they are linked in packages.json using "file:../local_modules/someModule"

When I package with node-lambda the final .zip file contains symkink to ../local_modules and not actual files. Running this on AWS will fail due to missing files.

I tried numerous packing options such as fixing archiver, packaging with install_local - none of them seems to support having "shared" local modules.
