### ISSUE TITLE
SQS event source fails with 'StartingPosition is not valid for SQS event sources'

### ISSUE THREAD

**Issue by mleiseca** [motdotla/node-lambda#466]
I'd like to use an SQS queue as an event source, but there's a default value being provided for 'StartingPosition'. StartingPosition is not a valid value for SQS events.

Would it work to change [this line](https://github.com/motdotla/node-lambda/blob/32a7c6de118d4aadbf9b87c0ee1e289e41b9d631/lib/main.js#L650) to only provide a default 'StartingPosition' if EventSourceArn doesn't start with 'arn:aws:sqs'?

Here's the eventSources.json that I'm using (with queue names changed)
```json

{
  "EventSourceMappings": [
    {
      "EventSourceArn": "arn:aws:sqs:us-east-1:sqs-queuename1",
      "BatchSize": 1,
      "Enabled": true
    },
    {
      "EventSourceArn": "arn:aws:sqs:us-east-1:sqs-queuename2",
      "BatchSize": 1,
      "Enabled": true
    }
  ]
}
```

The error message:
```
{ InvalidParameterValueException: StartingPosition is not valid for SQS event sources.
    at Object.extractError (/usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'StartingPosition is not valid for SQS event sources.',
```

**Comment by abetomo** [comment]
Thank you for the report.
SQS event was unsupported.
I'll fix it.

**Comment by mleiseca** [comment]
Thanks for the quick response! I've made that change locally and deploying SQS event sources works when it's in place.
