### ISSUE TITLE
Cert error

### ISSUE THREAD

**Issue by corydorning** [motdotla/node-lambda#515]
When trying to deploy, I keep getting a cert error. I am behind a proxy, which i've specified via `--proxy "http://myproxy.com:8080"`. The error is as follows:

```
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
  message: 'self signed certificate in certificate chain',
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 'lambda.us-east-1.amazonaws.com',
  retryable: true,
  time: 2020-01-13T19:42:16.842Z }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld@1.0.0 deploy: `node-lambda deploy --configFile .env --proxy http://myproxy.com:8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the helloworld@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2020-01-13T19_42_16_905Z-debug.log
```

**Comment by DeviaVir** [comment]
Have you seen https://stackoverflow.com/questions/9626990/receiving-error-error-ssl-error-self-signed-cert-in-chain-while-using-npm ?

**Comment by corydorning** [comment]
yeah i have. none of it fixed the issue. tried adding ca file reference, tried  ssl verify...none of it fixed the issue.
