### ISSUE TITLE
Lambda deployment not working

### ISSUE THREAD

**Issue by ankur-ps** [motdotla/node-lambda#573]
From past 5 days, we are seeing following errors in the deployment. It might be related to the Latest release at AWS
https://aws.amazon.com/de/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/ 
But can we have any updates around it please in this package?

`{ ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1::function:ht-create-survey-stage
    at Object.extractError (/var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/lang/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:690:12)
  message:
   'The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1::function:ht-create-survey-stage',
  code: 'ResourceConflictException',
  time: 2021-09-20T12:15:35.383Z,
  requestId: 'eda4992d-e1f9-4a8f-9d1e-8d61f0a44d85',
  statusCode: 409,
  retryable: false,
  retryDelay: 83.27273816538587 }`

**Comment by abetomo** [comment]
Thanks for the report.
I have opened a PR.
#575
