### ISSUE TITLE
How do I use the DEPLOY_USE_S3 option?

### ISSUE THREAD

**Issue by cfletch** [motdotla/node-lambda#587]
Hi

I'm trying to use the `-B` option in `node-lambda deploy`, but am still getting `RequestEntityTooLargeException`.

Full stack trace:
```
Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation
=> Retrying
RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation
    at Object.extractError (/home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v17.0.1/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:688:12) {
  code: 'RequestEntityTooLargeException',
  time: 2021-11-14T22:36:53.529Z,
  requestId: 'bbb55016-16d6-440a-86a8-98bdee9ee34d',
  statusCode: 413,
  retryable: false,
  retryDelay: 31.59037646361986
}
```

Here's my command: `node-lambda deploy -e production -n myLambda -a $AWS_ACCESS_KEY -s $AWS_ACCESS_SECRET -u nodejs10.x -t 15 -m 1600 -o arn:aws:dummy -g sg -b subnet -r eu-west-1 -B newBucket`

Am I using this option correctly?

**Comment by abetomo** [comment]
`-B` is a boolean.
(You cannot specify the bucket name as a command line argument.)


To specify the bucket name or S3 key prefix, use environment variables.
For example, you can set it to .env as follows.


```shell
S3_US_WEST_1_BUCKET=test_aaa
S3_US_WEST_1_PREFIX=bbb
```

In this case, the s3 key ::
`test_aaa/bbb/deploy-package-${FunctionName}.zip`

**Comment by cfletch** [comment]
thanks for quick response @abetomo! That works for me now.

Agree something on the readme will help others.

Cheers!
